#!/bin/bash

PACKAGE_VERSION=`grep '"version":' ./package.json | cut -d '"' -f4`
PACKAGE_LOCK_VERSION=`node -p "require('./package-lock.json').version"`
PACKAGE_LOCK_VERSION_2=`node -p "require('./package-lock.json').packages[''].version"`

# For debugging:
# echo x${PACKAGE_VERSION}x
# echo x${PACKAGE_LOCK_VERSION}x
# echo x${PACKAGE_LOCK_VERSION_2}x

EXITCODE=0

if [[ x${PACKAGE_VERSION}x != x${PACKAGE_LOCK_VERSION}x ]]; then
	echo Version different in package.json and package-lock.json
	EXITCODE=-1
fi

if [[ x${PACKAGE_VERSION}x != x${PACKAGE_LOCK_VERSION_2}x ]]; then
	echo Version different in package.json and the packages property in package-lock.json
	EXITCODE=-1
fi

exit $EXITCODE
