name: End-to-end tests
on:
  push:
    branches:
      - master
      - dev
    tags:
      - v*
  # pull_request:
  #   branches:
  #     - dev
  #     - master
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
