name: End-to-end tests
# on:
#   push:
#     branches:
#       - master
#       - release-candidate
#       - release
#     tags:
#       - v*
#   pull_request:
#     branches:
#       - master
#       - release-candidate
#       - release
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v4.1.7
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Setup nodejs
        # https://github.com/actions/setup-node/releases/tag/v4.0.3
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: ${{ matrix.node-version }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        # https://github.com/cypress-io/github-action/releases/tag/v6.5.0
        uses: cypress-io/github-action@59810ebfa5a5ac6fcfdcfdf036d1cd4d083a88f2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
