name: tests
on:
  push:
    branches:
    - master
    - dev
    tags:
    - v*
  pull_request:
    branches:
    - dev
    - master
jobs:
  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 40  # default is 360
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Start
      run: export NODE_OPTIONS=--max_old_space_size=2048; npm start