name: tests
on:
  push:
    branches:
    - master
    - dev
    tags:
    - v*
  pull_request:
    branches:
    - dev
    - master
jobs:
  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 40  # default is 360
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Install gettext
      run: sudo apt-get install gettext
    - name: Check version
      run: make check_version
    - name: Pot file
      run: make check_pot
    - name: Po file
      run: make check_po
    - name: i18n
      run: make i18n
    - name: Start
      run: npm start & npx wait-on http://localhost:3000
      env:
        CI: true
